### ISSUE TITLE
Use of DEBUG Symbol

### ISSUE THREAD

**Issue by chadefranklin** [MrUnbelievable92/MaxMath#11]
DEBUG define symbol is always active in the Unity Editor which is leading to Assertions being active... slowing performance and cluttering the Burst Inspector with many branches. I'm not sure what the best remedy for this is. Maybe using ENABLE_UNITY_COLLECTIONS_CHECKS instead so at least Burst can get rid of them.

**Comment by MrUnbelievable92** [comment]
ENABLE_UNITY_COLLECTIONS_CHECKS would add an unnecessary dependency on the Unity.Collections package.
There is a functionality for disabling all/some assertions in the editor via `Window/C# Dev Tools/Manage Safety Checks...` for performance tests or editor scripts.

This is technically closed but I'll pin it for others to read.
