### ISSUE TITLE
NextGreater Appears to be Broken

### ISSUE THREAD

**Issue by chadefranklin** [MrUnbelievable92/MaxMath#13]
This functionality should be very useful, but NextGreater doesn't seem to work for me (Bursted code or not). Not much else to say about it, but here are some screenshots:

![Screenshot_1](https://user-images.githubusercontent.com/55667412/226172662-3c596142-cc5d-4970-baec-66bd6f87213a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/55667412/226172674-aa2ba12a-fc9f-4d64-abe2-c61f78f26bf4.jpg)

**Comment by chadefranklin** [comment]
After some more investigation, I see NextGreater is indeed working properly but the default float.ToString() won't display the difference.

![Screenshot_3](https://user-images.githubusercontent.com/55667412/226174035-be0c2d10-94b8-4315-b100-46ae8bb73766.jpg)

**Comment by chadefranklin** [comment]
Closing as the original issue is mistaken.

**Comment by MrUnbelievable92** [comment]
I'm a little late to the party but yes - the standard ToString method often will indicate that there is no difference - at least for 32 bit floats. The respective 8- and 16 bit float inputs and outputs will always be different when converted to a string; for 32 bit floats it's 50/50 (below 2^23) and 64 bit float input- and output strings will almost never differ (below 2^52).
Unit tests for this category of functions use all float comparison operators C# gives you. IEEE 754 and thus the hardware guarantees their accuracy even with the smallest of differences, at least.
