### ISSUE TITLE
Accessing index of matrices adds BurstString.cs (among others) additions to assembly

### ISSUE THREAD

**Issue by fmarqvardt** [MrUnbelievable92/MaxMath#17]
```
[BurstCompile]
public struct J6 : IJob

{
    [WriteOnly] public ushort16 test;
    public void Execute()
    {
        test[0] = 5;
    }
}
```
Compiles into:
![image](https://github.com/user-attachments/assets/be942f0f-1b7f-4e85-a4dc-be96f296e863)

Meanwhile, a normal float4 (for example) compiles correctly:
```
[BurstCompile]
public struct J6 : IJob
{
    [WriteOnly] public float4 test;
    public void Execute()
    {
        test[0] = 5;
    }
}
```
![image](https://github.com/user-attachments/assets/b1cb1c11-7050-42f8-aeac-90f12bb1c6f6)

Tested in Unity 6 Preview (6000.0.21f1) Burst 1.71

**Comment by fmarqvardt** [comment]
Apparently it's not just by accessing the indexes. The code below has the same behavior.
```
[BurstCompile]
public struct J5 : IJob
{
    public ushort16 result;
    public void Execute()
    {
        ushort16 test = new ushort16();
        var mask = maxmath.bitmask16(test, new ushort16(15));  //Adds BurstString.cs
        var or = test | mask;
        result = or;
    }
}
```

**Comment by chadefranklin** [comment]
Can you check if you have assertions enabled in the window?:
"Window -> C# Dev Tools -> Manage Safety Checks..."

**Comment by fmarqvardt** [comment]
That was it! Turning them off made it compile correctly. Thanks.
