### ISSUE TITLE
Inns

### ISSUE THREAD

**Issue by Neovariance** [MrUnbelievable92/MaxMath#4]
This was due to the GUID of devtools being wrong in the math assembly definition, I could fix it easily by adding the dev tools depency. 

It would probably be more reliable with the use guids checkbox set to off in assembly definitions

**Comment by MrUnbelievable92** [comment]
That's an annoying bug for the user, which hasn't occurred on my machine.

Fixed in next release (v2.2.0 - probably done by tomorrow)

**Comment by MrUnbelievable92** [comment]
Fixed in [Version 2.2.0](https://github.com/MrUnbelievable92/MaxMath/releases/tag/2.2.0)
