### ISSUE TITLE
Can't add package from git URL because no .meta files

### ISSUE THREAD

**Issue by HyperionSniper** [MrUnbelievable92/MaxMath#5]
All the files in the repo are ignored because they don't have .meta files, and Unity won't generate .meta files for files in immutable folders (such as Packages).

**Comment by MrUnbelievable92** [comment]
God, that's annoying - thank you for letting me know.

I once again have another **HUGE** release coming. Just another few ten thousand lines of unit tests and it will be fixed... Within 1-2 weeks.

**Comment by MrUnbelievable92** [comment]
Just as an update: I need another week for the next release.

Hundreds of bugs appeared due to major refactoring or rather a rewrite of the entire library... They are being fixed at the moment and there are still 2 - 3 manageable TODOs on my list.

**Comment by MrUnbelievable92** [comment]
fixed in [version 2.3.0](https://github.com/MrUnbelievable92/MaxMath/releases/tag/2.3.0)

also fixed in [C# Dev Tools 1.0.8](https://github.com/MrUnbelievable92/C-Sharp-Dev-Tools/releases/tag/1.0.8)
